// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RazorCms.Data.Models
{
    [Table("Contact")]
    public partial class Contact
    {
        [Column("ContactID")]
        public int ContactId { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(50)]
        [Display(Name = "Work Phone")]
        public string WorkPhone { get; set; }

        [StringLength(50)]
        [Display(Name = "Mobile Phone")]
        public string MobilePhone { get; set; }

        [StringLength(50)]
        [Display(Name = "Home Phone")]
        public string HomePhone { get; set; }

        [StringLength(50)]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [StringLength(50)]
        [Display(Name = "Work Title")]
        public string WorkTitle { get; set; }

        [Column("CompanyID")]
        [Display(Name = "Company")]
        public int? CompanyId { get; set; }

        [ForeignKey("CompanyId")]
        public Company Company { get; set; }

    }
}